'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace WebApplication18


    Partial Public Class [Default]

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' ASPxFormLayout1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxFormLayout1 As Global.DevExpress.Web.ASPxFormLayout

        ''' <summary>
        ''' CmbSalesPerson control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected CmbSalesPerson As Global.DevExpress.Web.ASPxComboBox

        ''' <summary>
        ''' CmbCountry control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected CmbCountry As Global.DevExpress.Web.ASPxComboBox

        ''' <summary>
        ''' CmbCity control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected CmbCity As Global.DevExpress.Web.ASPxComboBox

        ''' <summary>
        ''' SqlDataSource1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

        ''' <summary>
        ''' SqlDataSource2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected SqlDataSource2 As Global.System.Web.UI.WebControls.SqlDataSource

        ''' <summary>
        ''' SqlDataSource3 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected SqlDataSource3 As Global.System.Web.UI.WebControls.SqlDataSource

        ''' <summary>
        ''' ASPxDashboard1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxDashboard1 As Global.DevExpress.DashboardWeb.ASPxDashboard
    End Class
End Namespace
